runtime: python312

# Environment variables
env_variables:
  ODM_PORT: 8080
  ODM_DEBUG: false

# Automatic scaling (optional but recommended)
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Static file handlers
handlers:
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon\.ico
    
  - url: /static
    static_dir: static
    # Optional: Set cache control for static files
    http_headers:
      Cache-Control: "public, max-age=3600"

# Use automatic entrypoint detection (recommended)
# GAE will automatically detect Flask apps
# entrypoint: gunicorn -b :$PORT main:app  # Remove this line