runtime: python311

handlers:
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
  - url: /static
    static_dir: static

entrypoint: gunicorn -b :$PORT main:app
