application: orejademorfeo
runtime: python27
api_version: 1
threadsafe: false
version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /static
  static_dir: static
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /css
  static_dir: static/css
- url: /font
  static_dir: static/font
- url: /.*
  script: nombres.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest