version: '3.8'

services:
  orejademorfeo:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ODM_DEBUG=true
      - ODM_PORT=8080
    volumes:
      # Mount source code for development (optional)
      - .:/opt/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Add nginx proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - orejademorfeo
  #   restart: unless-stopped