# coding: utf-8
'''
Created on 19/05/2013
@author: Óscar Gómez Alcañiz <oscar.gomez.london@gmail.com>
'''

class Palabras:
    adjetivos = [ "maldito",
        "enfermo",
        "bárbaro",
        "cretino",
        "tremendo",
        "celebérrimo",
        "esperpéntico",
        "fatídico",
        "magnífico",
        "soberbio",
        "hábil",
        "inútil",
        "obsoleto",
        "loco",
        "alto",
        "atlético",
        "bajo",
        "robusto",
        "corpulento",
        "delgado",
        "fuerte",
        "gordo",
        "deportivo",
        "joven",
        "canijo",
        "barrigudo",
        "flaco",
        "delgado",
        "viejo",
        "sano",
        "descuidado",
        "chillón",
        "elegante",
        "discreto",
        "feo",
        "alegre",
        "feo",
        "bonito",
        "pobre",
        "sencillo",
        "sofisticado",
        "Inmóvil",
        "quieto",
        "estático",
        "rápido",
        "dinámico",
        "lento",
        "parsimonioso",
        "majestuoso",
        "alegre",
        "animado",
        "moderno",
        "tradicional",
        "triste",
        "descuidado",
        "deportivo",
        "tranquilo",
        "nervioso",
        "pesimista",
        "callado",
        "hablador",
        "perezoso",
        "trabajador",
        "característico",
        "sincero",
        "optimista",
        "majo",
        "tímido",
        "abierto",
        "nervioso",
        "egoísta",
        "imaginativo",
        "sensible",
        "trabajador",
        "solidario",
        "inseguro",
        "vago",
        "cariñoso",
        "cerrado",
        "insolidario",
        "irresponsable",
        "alegre",
        "pesimista",
        "reflexivo",
        "zalamero",
        "valiente",
        "temerario",
        "cobarde",
        "prudente",
        "arrogante",
        "orgulloso",
        "altivo",
        "soberbio",
        "engreído",
        "antipático",
        "atrevido",
        "serio",
        "educado",
        "exigente",
        "malhumorado",
        "valiente",
        "fanfarrón",
        "feliz",
        "chulo",
        "grosero",
        "presumido",
        "confiado",
        "cobarde",
        "grosero",
        "chiflado",
        "simpático",
        "sincero",
        "sociable",
        "solitario",
        "decidido",
        "divertido",
        "inteligente",
        "campechano",
        "risueño",
        "llorón",
        "tímido" ]

    propios = { "Nerea" : "f",
        "Julia" : "f",
        "Van Gogh" : "m",
        "Morfeo" : "m",
        "Goliat" : "m",
        "Caín" : "m",
        "Atenea" : "f",
        "Gabriel" : "m",
        "Belcebú" : "m",
        "Shakira" : "f",
        "Selene" : "f",
        "Abelard" : "m",
        "Adalgisa" : "f",
        "Adalgiso" : "m",
        "Adalia" : "f",
        "Adelbert" : "m",
        "Adelfried" : "m",
        "Adelina" : "f",
        "Adelino" : "m",
        "Adelmo" : "m",
        "Ademaro" : "m",
        "Adler" : "m",
        "Adolfina" : "f",
        "Adolph" : "m",
        "Agneta" : "f",
        "Ahren" : "m",
        "Alaric" : "m",
        "Albert" : "m",
        "Alberta" : "f",
        "Aldous" : "m",
        "Alger" : "m",
        "Alicia" : "f",
        "Alphonse" : "m",
        "Amara" : "f",
        "Ancel" : "m",
        "Antje" : "f",
        "Arabelle" : "f",
        "Arnold" : "m",
        "Aubrey" : "f",
        "Ava" : "f",
        "Baldwin" : "m",
        "Barend" : "m",
        "Bergen" : "m",
        "Berit" : "f",
        "Bernadette" : "f",
        "Bernard" : "m",
        "Berta" : "f",
        "Bertram" : "m",
        "Bingham" : "m",
        "Blaz" : "m",
        "Bluma" : "f",
        "Brandeis" : "m",
        "Brunhilde" : "f",
        "Burke" : "m",
        "Callan" : "f",
        "Carleigh" : "f",
        "Caroline" : "f",
        "Cecania" : "f",
        "Chay" : "f",
        "Chloris" : "f",
        "Arcilla" : "f",
        "Conrado" : "m",
        "Cort" : "m",
        "Dagmar" : "f",
        "Dagna" : "f",
        "Dagobert" : "m",
        "Dama" : "f",
        "Derek" : "m",
        "Dieter" : "m",
        "Dietlinde" : "f",
        "Dustin" : "m",
        "Ebba" : "f",
        "Eberhard" : "m",
        "Edwin" : "m",
        "Edwina" : "f",
        "Egbert" : "m",
        "Egmont" : "m",
        "Eldwin" : "m",
        "Elisabeth" : "f",
        "Ellery" : "m",
        "Esmeril" : "m",
        "Emil" : "m",
        "Emily" : "f",
        "Emma" : "f",
        "Erika" : "f",
        "Ernest" : "m",
        "Ernestine " : "f",
        "Fancy" : "f",
        "Fatima" : "f",
        "Faye" : "f",
        "Felicia" : "f",
        "Filipa" : "f",
        "Fiona" : "f",
        "Flora" : "f",
        "France" : "f",
        "Frankie" : "f",
        "Gaea" : "f",
        "Gaelle" : "f",
        "Garance" : "f",
        "Gea" : "f",
        "Georgette" : "f",
        "Georgia" : "f",
        "Georgina" : "f",
        "Gina" : "f",
        "Ginger" : "f",
        "Gisele" : "f",
        "Gladys" : "f",
        "Grace" : "f",
        "Gwendolyn" : "f",
        "Hannah" : "f",
        "Hayley" : "f",
        "Heather" : "f",
        "Heidi" : "f",
        "Helen" : "f",
        "Hélèna" : "f",
        "Holly" : "f",
        "Hortense" : "f",
        "Iana" : "f",
        "Ilana" : "f",
        "Ilona" : "f",
        "Ines" : "f",
        "Ingrid" : "f",
        "Irene" : "f",
        "Irina" : "f",
        "Irma" : "f",
        "Isabella" : "f",
        "Felix" : "m",
        "Flavio" : "m",
        "Forest" : "m",
        "Fox" : "m",
        "Francis" : "m",
        "Franck" : "m",
        "Francklin" : "m",
        "Frank" : "m",
        "Frankie" : "m",
        "Franklin" : "m",
        "Franky" : "m",
        "Frederic" : "m",
        "Friday" : "m",
        "Gaby" : "m",
        "Gael" : "m",
        "Gally" : "m",
        "Garry" : "m",
        "Gary" : "m",
        "Gaspard" : "m",
        "Gautier" : "m",
        "Gavin" : "m",
        "Gaye" : "m",
        "Gaylord" : "m",
        "Gemini" : "m",
        "Geoffrey" : "m",
        "George" : "m",
        "Georges" : "m",
        "Geremy" : "m",
        "Gerhard" : "m",
        "Gilbert" : "m",
        "Gilberto" : "m",
        "Giles" : "m",
        "Gillian" : "m",
        "Glenn" : "m",
        "Graham" : "m",
        "Gregory" : "m",
        "Gypsy" : "m",
        "Hadrien" : "m",
        "Hans" : "m",
        "Harold" : "m",
        "Harrison" : "m",
        "Harry" : "m",
        "Harvey" : "m",
        "Hassan" : "m",
        "Henri" : "m",
        "Henry" : "m",
        "Herbert" : "m",
        "Homer" : "m",
        "Howard" : "m",
        "Hubert" : "m",
        "Hudson" : "m",
        "Hugo" : "m",
        "Iain" : "m",
        "Ian" : "m",
        "Ianis" : "m",
        "Iban" : "m",
        "Ibrahim" : "m",
        "Ilan" : "m",
        "Ilhan" : "m",
        "Ilias" : "m",
        "Isaac" : "m",
        "Isis" : "m",
        "Ivan" : "m",
        "Laetitia" : "f",
        "Laïla" : "f",
        "Lana" : "f",
        "Lara" : "f",
        "Larissa" : "f",
        "Laura" : "f",
        "Lauralie" : "f",
        "Lauranne" : "f",
        "Laure" : "f",
        "Laurélie" : "f",
        "Laureline" : "f",
        "Lauréna" : "f",
        "Laurence" : "f",
        "Laurène" : "f",
        "Laurette" : "f",
        "Laurie" : "f",
        "Laurina" : "f",
        "Laurine" : "f",
        "Léa" : "f",
        "Léana" : "f",
        "Léandre" : "f",
        "Léane" : "f",
        "Leevan" : "f",
        "Léone" : "f",
        "Léonie" : "f",
        "Léonore" : "f",
        "Lila" : "f",
        "Lilas" : "f",
        "Liliane" : "f",
        "Lilianne" : "f",
        "Lilou" : "f",
        "Lina" : "f",
        "Linda" : "f",
        "Line" : "f",
        "Lisa" : "f",
        "Lisange" : "f",
        "Lise" : "f",
        "Lison" : "f",
        "Loana" : "f",
        "Loane" : "f",
        "Loanne" : "f",
        "Lohane" : "f",
        "Loïc" : "f",
        "Loïca" : "f",
        "Loïs" : "f",
        "Lola" : "f",
        "Lolita" : "f",
        "Lorène" : "f",
        "Lorette" : "f",
        "Loriane" : "f",
        "Lorianne" : "f",
        "Lorie" : "f",
        "Lorine" : "f",
        "Lorraine" : "f",
        "Lorriane" : "f",
        "Lou" : "f",
        "Louane" : "f",
        "Louisa" : "f",
        "Louise" : "f",
        "Louisette" : "f",
        "Luce" : "f",
        "Lucette" : "f",
        "Lucie" : "f",
        "Lucile" : "f",
        "Lucine" : "f",
        "Lucrèce" : "f",
        "Ludivine" : "f",
        "Luna" : "f",
        "Lydia" : "f",
        "Lydie" : "f",
        "Lyne" : "f",
        "Lys" : "f",
        "Lysange" : "f",
        "Lyséa" : "f",
        "Lysiane" : "f",
        "Lysianne" : "f",
        "Macha" : "f",
        "Madeleine" : "f",
        "Madinina" : "f",
        "Madisson" : "f",
        "Maëlann" : "f",
        "Maelia" : "f",
        "Maëline" : "f",
        "Maëlla" : "f",
        "Maëlle" : "f",
        "Maëly" : "f",
        "Maëlys" : "f",
        "Maëlyss" : "f",
        "Maéna" : "f",
        "Maeva" : "f",
        "Maeve" : "f",
        "Magali" : "f",
        "Magalie" : "f",
        "Magatte" : "f",
        "Magdalène" : "f",
        "Maggy" : "f",
        "Maguy" : "f",
        "Mahélie" : "f",
        "Maï" : "f",
        "Maïlis" : "f",
        "Maïly" : "f",
        "Maïlys" : "f",
        "Maire-Christine" : "f",
        "Maïté" : "f",
        "Maiwen" : "f",
        "Maïwenn" : "f",
        "Malaury" : "f",
        "Malorie" : "f",
        "Manon" : "f",
        "Manu" : "f",
        "Maoline" : "f",
        "Marceline" : "f",
        "Marcelle" : "f",
        "Margareth" : "f",
        "Margaux" : "f",
        "Margot" : "f",
        "Marguerite" : "f",
        "Maria" : "f",
        "Mariana" : "f",
        "Marianna" : "f",
        "Marianne" : "f",
        "Marie" : "f",
        "Marie-Ange" : "f",
        "Marie-Anne" : "f",
        "Marie-Antoinette" : "f",
        "Marie-Claude" : "f",
        "Marie-Ève" : "f",
        "Marie-Françoise" : "f",
        "Marie-Hélène" : "f",
        "Marie-Jeanne" : "f",
        "Marie-Josée" : "f",
        "Marie-Laure" : "f",
        "Marie-Line" : "f",
        "Marie-Neige" : "f",
        "Marie-Noël" : "f",
        "Marie-Pier" : "f",
        "Marie-Reine" : "f",
        "Marie-Soleil" : "f",
        "Marie-Sophie" : "f",
        "Marie-Thérèse" : "f",
        "Marielle" : "f",
        "Mariette" : "f",
        "Marilou" : "f",
        "Marilyne" : "f",
        "Marina" : "f",
        "Marine" : "f",
        "Marion" : "f",
        "Marjolaine" : "f",
        "Marjorie" : "f",
        "Marlène" : "f",
        "Martha" : "f",
        "Marylène" : "f",
        "Marylise" : "f",
        "Maryse" : "f",
        "Maryvonne" : "f",
        "Mathilda" : "f",
        "Mathilde" : "f",
        "Mathis" : "f",
        "Matisse" : "f",
        "Maud" : "f",
        "Maude" : "f",
        "Maurane" : "f",
        "Maureen" : "f",
        "Mauricette" : "f",
        "Maurine" : "f",
        "Maxine" : "f",
        "Maya" : "f",
        "Mayliss" : "f",
        "Mazarine" : "f",
        "Mégane" : "f",
        "Méghane" : "f",
        "Mélanie" : "f",
        "Mélia" : "f",
        "Mélina" : "f",
        "Mélinda" : "f",
        "Méline" : "f",
        "Melissa" : "f",
        "Mélissandre" : "f",
        "Mélodie" : "f",
        "Mélys" : "f",
        "Méryl" : "f",
        "Mia" : "f",
        "Michèle" : "f",
        "Micheline" : "f",
        "Miléna" : "f",
        "Milie" : "f",
        "Mina" : "f",
        "Mireille" : "f",
        "Monica" : "f",
        "Monique" : "f",
        "Morgane" : "f",
        "Moune" : "f",
        "Murielle" : "f",
        "Mylène" : "f",
        "Myriam" : "f",
        "Myrtille" : "f",
        "Nadège" : "f",
        "Nadia" : "f",
        "Nadina" : "f",
        "Nadine" : "f",
        "Naëlle" : "f",
        "Naéva" : "f",
        "Nancy" : "f",
        "Naomi" : "f",
        "Naomie" : "f",
        "Natacha" : "f",
        "Natalina" : "f",
        "Nath" : "f",
        "Nathalie" : "f",
        "Nawelle" : "f",
        "Néhémie" : "f",
        "Neige" : "f",
        "Nélie" : "f",
        "Nelly" : "f",
        "Nicole" : "f",
        "Ninon" : "f",
        "Noëlla" : "f",
        "Noelle" : "f",
        "Noémie" : "f",
        "Nolan" : "f",
        "Nolwenn" : "f",
        "Norah" : "f",
        "Océane" : "f",
        "Océanne" : "f",
        "Odette" : "f",
        "Odile" : "f",
        "Olive" : "f",
        "Olivia" : "f",
        "Ombeline" : "f",
        "Ombline" : "f",
        "Ondine" : "f",
        "Ophélie" : "f",
        "Oriane" : "f",
        "Orlane" : "f",
        "Pascale" : "f",
        "Pascaline" : "f",
        "Patricia" : "f",
        "Paule" : "f",
        "Paulette" : "f",
        "Pauline" : "f",
        "Peggy" : "f",
        "Pélagie" : "f",
        "Pénélope" : "f",
        "Perline" : "f",
        "Perrine" : "f",
        "Phoenix" : "f",
        "Pierrette" : "f",
        "Poca" : "f",
        "Prescilla" : "f",
        "Prescillia" : "f",
        "Prudence" : "f",
        "Rachèle" : "f",
        "Rania" : "f",
        "Raphaelle" : "f",
        "Ravina" : "f",
        "Raymonde" : "f",
        "Rébecca" : "f",
        "Régine" : "f",
        "Reine" : "f",
        "Réjane" : "f",
        "Renaud" : "f",
        "Renée" : "f",
        "Rita" : "f",
        "Rolande" : "f",
        "Romane" : "f",
        "Rosa" : "f",
        "Rosaire" : "f",
        "Rosalie" : "f",
        "Rose" : "f",
        "Roseline" : "f",
        "Roselyne" : "f",
        "Roxane" : "f",
        "Roxanne" : "f",
        "Rozenn" : "f",
        "Sabine" : "f",
        "Sabrina" : "f",
        "Salomé" : "f",
        "Samantha" : "f",
        "Sandra" : "f",
        "Sandrine" : "f",
        "Sara" : "f",
        "Sarah" : "f",
        "Sarah" : "f",
        "Sasha" : "f",
        "Sélène" : "f",
        "Séréna" : "f",
        "Servane" : "f",
        "Séverine" : "f",
        "Sibylle" : "f",
        "Sidonie" : "f",
        "Simone" : "f",
        "Soizic" : "f",
        "Solane" : "f",
        "Solange" : "f",
        "Soleil" : "f",
        "Solène" : "f",
        "Solenn" : "f",
        "Solenne" : "f",
        "Sonia" : "f",
        "Sophie" : "f",
        "Stéphanie" : "f",
        "Stévina" : "f",
        "Susanne" : "f",
        "Susie" : "f",
        "Suzanne" : "f",
        "Suzette" : "f",
        "Suzie" : "f",
        "Sylvaine" : "f",
        "Sylvette" : "f",
        "Sylviane" : "f",
        "Sylvie" : "f",
        "Syrielle" : "f",
        "Raphaël" : "m",
        "Raymond" : "m",
        "Réchard" : "m",
        "Régis" : "m",
        "Réjean" : "m",
        "Rémi" : "m",
        "Rémy" : "m",
        "Rénald" : "m",
        "Renan" : "m",
        "René" : "m",
        "Reynald" : "m",
        "Richard" : "m",
        "Riton" : "m",
        "Robert" : "m",
        "Robin" : "m",
        "Rodolphe" : "m",
        "Roger" : "m",
        "Roland" : "m",
        "Romain" : "m",
        "Roman" : "m",
        "Romaric" : "m",
        "Roméo" : "m",
        "Romuald" : "m",
        "Rudolph" : "m",
        "Rudy" : "m",
        "Pamphile" : "m",
        "Pascal" : "m",
        "Patrice" : "m",
        "Patrick" : "m",
        "Paul" : "m",
        "Paul-Loup" : "m",
        "Philippe" : "m",
        "Phillipe" : "m",
        "Phoenix" : "m",
        "Pierre" : "m",
        "Pierre-Loup" : "m",
        "Pierrick" : "m",
        "Poupi" : "m",
        "Octave" : "m",
        "Odoric" : "m",
        "Olivier" : "m",
        "Ollivier" : "m",
        "Orville" : "m",
        "Oscar" : "m",
        "Napoléon" : "m",
        "Nathan" : "m",
        "Nazaire" : "m",
        "Néo" : "m",
        "Nestor" : "m",
        "Nicodème" : "m",
        "Nicolas" : "m",
        "Noah" : "m",
        "Noam" : "m",
        "Noan" : "m",
        "Noé" : "m",
        "Noël" : "m",
        "Nolan" : "m",
        "Norbert" : "m",
        "Normand" : "m",
        "Maciel" : "m",
        "Maël" : "m",
        "Malo" : "m",
        "Manuel" : "m",
        "Marc" : "m",
        "Marc-Antoine" : "m",
        "Marc-Olivier" : "m",
        "Marceau" : "m",
        "Marcel" : "m",
        "Marco" : "m",
        "Marcus" : "m",
        "Marius" : "m",
        "Martial" : "m",
        "Martin" : "m",
        "Martine" : "m",
        "Matéo" : "m",
        "Mathias" : "m",
        "Mathieu" : "m",
        "Mathis" : "m",
        "Matthieu" : "m",
        "Maurice" : "m",
        "Max" : "m",
        "Maxance" : "m",
        "Maxence" : "m",
        "Maxime" : "m",
        "Maximilien" : "m",
        "Médéric" : "m",
        "Melchior" : "m",
        "Michael" : "m",
        "Michel" : "m",
        "Mickaël" : "m",
        "Mikaël" : "m",
        "Milou" : "m",
        "Moïse" : "m",
        "Moncef" : "m",
        "ambert" : "m",
        "Lancelot" : "m",
        "Laurent" : "m",
        "Lazare" : "m",
        "Lény" : "m",
        "Léo" : "m",
        "Léon" : "m",
        "Léonard" : "m",
        "Léopold" : "m",
        "Lilian" : "m",
        "Lionel" : "m",
        "Lisandru" : "m",
        "Loan" : "m",
        "Logan" : "m",
        "Loghan" : "m",
        "Lohann" : "m",
        "Loick" : "m",
        "Lorian" : "m",
        "Lorik" : "m",
        "Lothaire" : "m",
        "Louis" : "m",
        "Louis-Philippe" : "m",
        "Louka" : "m",
        "Loup" : "m",
        "Lubin" : "m",
        "Luc" : "m",
        "Lucas" : "m",
        "Lucien" : "m",
        "Ludovic" : "m",
        "Luka" : "m" }

    comunes = { "canto" : "m",
        "sonrisa" : "f",
        "oreja" : "f",
        "sueño" : "m",
        "error" : "m",
        "estigma" : "m",
        "trampa" : "f",
        "encanto" : "m",
        "ascenso" : "m",
        "descenso" : "m",
        "caída" : "f",
        "trapicheo" : "m",
        "asesinato" : "m",
        "silbido" : "m",
        "señal" : "f",
        "traición" : "f",
        "desengaño" : "m",
        "evolución" : "f",
        "salto" : "m",
        "desaparición" : "f",
        "frustración" : "f",
        "antojo" : "m",
        "pasión" : "f",
        "negación" : "f",
        "redención" : "f",
        "engaño" : "m",
        "berrido" : "m",
        "grito" : "m",
        "dolor" : "m",
        "preocupación" : "f",
        "lío" : "m",
        "vida" : "f",
        "balada" : "f",
        "canción" : "f",
        "gramola" : "f",
        "furia" : "f",
        "gratitud" : "f",
        "secreto" : "m",
        "obsesión" : "f",
        "teorema" : "m",
        "teoría" : "f",
        "conjetura" : "m" }

    def __init__( self, propios=None, comunes=None, adjetivos=None ):
        if propios != None: self.propios = dict( self.propios.items() + propios.items() )
        if comunes != None: self.comunes = dict( self.comunes.items() + comunes.items() )
        if adjetivos != None: self.adjetivos = dict( self.adjetivos.items() + adjetivos.items() )
